### ISSUE TITLE
Totally unrelated question

### ISSUE THREAD

**Issue by Matt-Hill-83** [MaximumADHD/Roblox-FFlag-Tracker#1]
Hi.  Sorry for polluting your Issues list with something unrelated to this repo, but you seem very knowledgable and I have a question for you.  I've been scripting Roblox for 4 months and I'm looking for a well architected sample project with lots of whistles and bells that I can use as a pattern for my rapidly spaghettifying project.  Do you happen to know where I could find one?  

Thanks and sorry again to bug you in your Issues tracker.

- matt

**Comment by Sparkypen7** [comment]
Please ask on the devforum next time. It's inappropriate to file an issue that's completely irrelevant to the subject.

Anyway, to answer your question, I would recommend peeking at these:
https://github.com/Kampfkarren/zombie-strike
https://github.com/RoVSRG/robeats-cs/

This one has iffy formatting, but is still decent:
 https://github.com/berezaa/vesteria/

**Comment by Matt-Hill-83** [comment]
Thanks so much for the links!
